class LoremIpsum {
  static const long =
      '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sit amet eleifend mauris. Vestibulum pretium non ipsum et malesuada. Ut dolor odio, finibus non massa sit amet, rhoncus ornare dui. Suspendisse faucibus, purus at dapibus elementum, turpis ipsum aliquet dolor, in efficitur ante libero ac nisl. In commodo, turpis nec laoreet fermentum, elit mi viverra quam, sed porta libero mauris sed leo. Fusce enim augue, congue a facilisis ac, suscipit rhoncus diam. Maecenas non sapien a augue placerat cursus ac eget erat.

Quisque volutpat pretium consequat. Fusce gravida et nisl vulputate interdum. Integer id volutpat sapien. Suspendisse id imperdiet ante. Cras eu nunc ipsum. Nunc accumsan tellus vitae imperdiet sagittis. Mauris accumsan tristique nulla, vitae ornare urna aliquet in.

Fusce finibus odio at eros pharetra gravida. Pellentesque ut tempor magna, id euismod tellus. Curabitur congue nec est ut luctus. Praesent blandit quis mauris eget rutrum. Pellentesque placerat condimentum blandit. Nullam varius, tellus at dictum fermentum, nulla nibh eleifend ipsum, at scelerisque lacus dolor elementum libero. Nam a facilisis mauris, a aliquam erat. Ut vel nulla ut dui rhoncus consequat porta ac mi. Sed sed elementum felis, in varius ligula. Donec fermentum lacus quis blandit tincidunt.

Morbi ac posuere arcu, nec porta dui. Phasellus et odio lacus. Vestibulum massa lectus, laoreet et mauris ac, faucibus mattis quam. Cras volutpat, elit venenatis tristique dignissim, tellus lorem porttitor justo, id ullamcorper quam dolor nec lectus. Duis fermentum tristique erat nec pellentesque. Pellentesque vestibulum dictum lorem sed pharetra. Proin nec ipsum id urna mollis dictum sit amet eget mi. Quisque eu sem vitae elit vestibulum blandit non id neque. Proin porta rutrum est id cursus. Vivamus ut ipsum dapibus risus scelerisque finibus non nec eros. Maecenas auctor arcu nec ante facilisis, eu ultricies dolor porttitor. Nulla sodales urna non diam luctus dictum. Suspendisse potenti. Proin suscipit, lectus at tristique pellentesque, nibh est eleifend sapien, ac finibus nisi metus vel sapien. Nam volutpat nisi in placerat pharetra.

In volutpat dignissim metus at finibus. Integer nec accumsan arcu. Cras varius odio sit amet imperdiet convallis. Nulla at laoreet arcu. Etiam scelerisque magna eget neque tempor, ac sagittis augue porttitor. Sed non blandit nisi. Nam vel maximus quam. Donec imperdiet sem justo, vitae porta velit ultrices vitae.''';
}
